server:
  port: 8889

spring:
  application:
    name: oauth

  datasource:
    url: jdbc:postgresql://172.18.0.24:5432/postgres?currentSchema=oauthserver
    username: postgres
    password: admin
  jpa:
    show-sql: true

    ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true

        # Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: update
        hbm2ddl:
          auto: update

oauth-conf:
  language: FRENCH

jwt:
    secret: mySecret
    expiration: 604800

certificate:
  alias: jwtcert
  nameAndPath: keystore.jks
  dn: CN=cn, O=o, L=L, ST=il, C= c
  algorithm: RSA
  bits: 1024
  signatureAlgorithm: SHA256WithRSAEncryption
  secureRandom: SHA1PRNG

server.servlet.context-path: /oauth

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.18.0.22:8761/eureka}